services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres-market
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB:-go-market-ai-db}

      REDIS_HOST: redis-market
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:?REDIS_PASSWORD is required}

      MINIO_END_POINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: false

    depends_on:
      postgres-market:
        condition: service_healthy
      redis-market:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: always

  postgres-market:
    image: postgres:18-alpine
    container_name: postgres-market
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB:-go-market-ai-db}
    ports:
      - "5432:5432"
    volumes:
      - market-pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${DOCKER_POSTGRES_DB:-go-market-ai-db}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis-market:
    image: redis:8.2-alpine
    container_name: redis-market
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD:?REDIS_PASSWORD is required}",
      ]
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?REDIS_PASSWORD is required}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - market-redisdata:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a ${REDIS_PASSWORD:?REDIS_PASSWORD is required} ping | grep -q PONG",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - app-network
    restart: always

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /var/log:/var/log:ro
      # nếu bạn muốn đọc log của container kiểu json-file:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped

volumes:
  market-pgdata:
  market-redisdata:
  miniodata:

networks:
  app-network:
    driver: bridge
