name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: go-ai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Sync project to server
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'bin' \
            --exclude 'dist' \
            --exclude 'app' \
            ./ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/

      - name: Deploy on server
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          set -e
          APP_PATH=${{ secrets.DEPLOY_PATH }}

          echo "ğŸ”§ Creating .env file..."
          cat << 'ENVEOF' > "$APP_PATH/.env"
          ${{ secrets.ENV_FILE }}
          ENVEOF

          echo "ğŸ“‚ Checking app folder..."
          if [ ! -d "$APP_PATH" ]; then
            echo "ğŸ“ Folder does not exist â€” creating..."
            cd "$APP_PATH"
            echo "â¬‡ï¸ Cloning new repository..."
            git clone git@github.com:${{ github.repository }}.git .
          else
            echo "ğŸ“ Folder exists â€” updating repository..."
            cd "$APP_PATH"
              echo "ğŸ”„ Pulling latest changes..."
              git fetch origin main
              git reset --hard origin/main
          fi

          echo "ğŸ§¹ Clearing Docker cache..."
              docker builder prune -af || true
              docker system prune -af || true
              docker buildx prune -af || true

          docker compose down
          docker compose up -d --build --remove-orphans
          docker image prune -f
          EOF
